name: CI Pipeline

on:
  push:
    branches:
      - Dev
      - QA
      - main

  pull_request:
    branches:
      - Dev
      - QA
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restaurar dependencias
        run: dotnet restore ./ReservaBook/ReservaBook.sln

      - name: Compilar proyecto
        run: dotnet build ./ReservaBook/ReservaBook.sln --no-restore --configuration Release

      - name: Ejecutar pruebas unitarias
        run: dotnet test ./ReservaBook/ReservaBook.sln --no-build --configuration Release --logger "trx"

